### ISSUE TITLE
Latest sqlite-web require extension none

### ISSUE THREAD

**Issue by edgd1er** [Py-KMS-Organization/py-kms#11]
with latest sqlite-web commits, extensions are expected and cannot be null. not a bug in this project, but has definitely an impact..

```
kms       | + /usr/bin/python3 /home/sqlite_web/sqlite_web.py -rx -e none -H 0.0.0.0 /db/pykms_database.db
kms       | Traceback (most recent call last):
kms       |   File "/home/sqlite_web/sqlite_web.py", line 898, in <module>
kms       |     main()
kms       |   File "/home/sqlite_web/sqlite_web.py", line 870, in main
kms       |     options.extensions)
kms       | AttributeError: 'Values' object has no attribute 'extensions'
```

**Comment by Matthew-Beckett** [comment]
@simonmicro called it

**Comment by edgd1er** [comment]
As suggested in pull request https://github.com/coleifer/sqlite-web/pull/91/files, a temporary fix may be included in Dockerfile to fix the problem.

```bash
sed -i '764s/--extension'\''/--extensions'\''/' /home/sqlite_web/sqlite_web.py
```
