### ISSUE TITLE
pytz missing

### ISSUE THREAD

**Issue by edgd1er** [Py-KMS-Organization/py-kms#3]
There is message error in the log: `kms       | Thu, 16 Sep 2021 05:17:00 WARNING  Module 'tzlocal' not available ! Request time not localized.`
Here is the code triggering the warning
pykms_Base L123: from pytz.exceptions import UnknownTimeZoneError
                     L131: except ImportError: ..... 

Adding the pytz package (pip3 install pytz), whatever is the timezone, I have that error. I can't see why it is related.ere 
Is there any reason ?

```
kms       | Traceback (most recent call last):
kms       |   File "pykms_Client.py", line 364, in <module>
kms       |     clt_main(with_gui = False)
kms       |   File "pykms_Client.py", line 280, in clt_main
kms       |     client_create(clt_sock)
kms       |   File "pykms_Client.py", line 240, in client_create
kms       |     parsed = MSRPCRespHeader(response)
kms       |   File "/home/py-kms/pykms_Dcerpc.py", line 641, in __init__
kms       |     MSRPCHeader.__init__(self, aBuffer, alignment)
kms       |   File "/home/py-kms/pykms_Dcerpc.py", line 588, in __init__
kms       |     Structure.__init__(self,data, alignment)
kms       |   File "/home/py-kms/pykms_Structure.py", line 117, in __init__
kms       |     self.fromString(data)
kms       |   File "/home/py-kms/pykms_Structure.py", line 174, in fromString
kms       |     self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode=dataClassOrCode, field=field[0])
kms       |   File "/home/py-kms/pykms_Structure.py", line 336, in unpack
kms       |     return self.unpack(two[0], data)
kms       |   File "/home/py-kms/pykms_Structure.py", line 392, in unpack
kms       |     return unpack(format, b(data))[0]
kms       | struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver_major | B=5 | ''[:1]'")
```

**Comment by simonmicro** [comment]
Sorry for answering so late - my notification were broken. I have trouble to understand what you are writing - is this broken after installing the package, or is it fixed by installing the missing package? I know that Python3 bricked `tzdata` recently...

**Comment by edgd1er** [comment]
Hello,

I still have an issue not the same issue though: no terminal detected , then try to start with gui, none found but another exception occured during first exception, ending in the app crashing.

pykms_misc L230 was changed to remove typefile, although some calls are performed with the removed arg.
`def check_dir(path, where, log_obj = None, argument = '-F/--logfile'):`
called by
`pykms_server L483: check_dir(srv_config['sqlite'], 'srv', log_obj=loggersrv.error, argument='-s/--sqlite', typefile='.db')`

**Comment by edgd1er** [comment]
:) I'm already on the next point, no tz defined in python possibly... still investigating. thanks to the nice logs, it should be easy to pinpoint.

**Comment by simonmicro** [comment]
Whuääää, why is every fix making something else going brrr? Sometime, just sometimes...

**Comment by edgd1er** [comment]
> > Whuääää, why is every fix making something else going brrr? Sometime, just sometimes...
> 
> My incomplete proposal for this change didn't help

something like this might be required to define TZ in the entrypoint, still working on it....
```
#Change timzeone if set
[[ -n ${TZ} ]] && [[ -f /usr/share/zoneinfo/${TZ} ]] && [[ -w /etc/localtime ]] && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime
#use UTC if not
[[ ! -f /etc/localtime ]] && ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
```

**Comment by simonmicro** [comment]
> Hello,
> 
> I still have an issue not the same issue though: no terminal detected , then try to start with gui, none found but another exception occured during first exception, ending in the app crashing.
> 
> pykms_misc L230 was changed to remove typefile, although some calls are performed with the removed arg. `def check_dir(path, where, log_obj = None, argument = '-F/--logfile'):` called by `pykms_server L483: check_dir(srv_config['sqlite'], 'srv', log_obj=loggersrv.error, argument='-s/--sqlite', typefile='.db')`
> 
> I guess this should be opened as a new issue...

Fixed in 3806c032142f1f086e6da1715a8c67648771d38d.
