### ISSUE TITLE
Unable to open database file in read-only mode. Ensure that the database exists in order to use read-only mode.

### ISSUE THREAD

**Issue by lepoarro** [Py-KMS-Organization/py-kms#48]
After latest docker update got the message: Unable to open database file in read-only mode. Ensure that the database exists in order to use read-only mode.

Debug log is here:

```
Fri, 17 Dec 2021 08:46:20 INFO Log level: DEBUG
Fri, 17 Dec 2021 08:46:20 INFO Setting timzeone to Europe/Kiev
Fri, 17 Dec 2021 08:46:20 INFO Setting gid to '1000'.
Fri, 17 Dec 2021 08:46:20 INFO Setting uid to '100'.
Fri, 17 Dec 2021 08:46:20 INFO Storing database file to /home/py-kms/db/pykms_database.db
Fri, 17 Dec 2021 08:46:20 DEBUG server_cmd: /usr/bin/python3 -u pykms_Server.py 0.0.0.0 1688 -l 1033 -c 26 -a 120 -r 10080 -w RANDOM -V DEBUG -F STDOUT -s /home/py-kms/db/pykms_database.db
Fri, 17 Dec 2021 08:46:21 INFO TCP server listening at 0.0.0.0 on port 1688
Fri, 17 Dec 2021 08:46:21 INFO HWID: E6C388F490944342
Fri, 17 Dec 2021 08:46:25 INFO Starting a dummy activation to ensure the database file is created
Fri, 17 Dec 2021 08:46:25 DEBUG client_cmd: /usr/bin/python3 -u pykms_Client.py 0.0.0.0 1688 -m Windows10 -n DummyClient -c ae3a27d1-b73a-4734-9878-70c949815218 -V DEBUG -F STDOUT
Fri, 17 Dec 2021 08:46:25 INFO Connecting to 0.0.0.0 on port 1688
Fri, 17 Dec 2021 08:46:25 INFO Connection successful !
Fri, 17 Dec 2021 08:46:25 INFO Connection accepted: 127.0.0.1:59122
Fri, 17 Dec 2021 08:46:25 INFO Sending RPC bind request...
Fri, 17 Dec 2021 08:46:25 INFO RPC bind request received.
Fri, 17 Dec 2021 08:46:25 DEBUG RPC Bind Request Bytes:

05000b13100000007400000001000000d016d0160000000002000000000001007521c8514e845047b0d8ec255555bc060100
0000045d888aeb1cc9119fe808002b10486002000000010001007521c8514e845047b0d8ec255555bc06010000002c1cb76c
12984045030000000000000001000000

Fri, 17 Dec 2021 08:46:25 DEBUG RPC Bind Request:

MSRPCHeader
ver_major: {5}
ver_minor: {0}
type: {11}
flags: {19}
representation: {16}
frag_len: {116}
auth_len: {0}
call_id: {1}
dataLen: {100}
pduData: {b'\xd0\x16\xd0\x16\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x01\x00u!\xc8QN\x84PG\xb0\xd8\x
ec%UU\xbc\x06\x01\x00\x00\x00\x04]\x88\x8a\xeb\x1c\xc9\x11\x9f\xe8\x08\x00+\x10H`\x02\x00\x00\x00\x0
1\x00\x01\x00u!\xc8QN\x84PG\xb0\xd8\xec%UU\xbc\x06\x01\x00\x00\x00,\x1c\xb7l\x12\x98@E\x03\x00\x00\x
00\x00\x00\x00\x00\x01\x00\x00\x00'}
_pad: {0}
pad: {''}
_sec_trailer: {0}
sec_trailer: {''}
auth_dataLen: {0}
auth_data: {''}

MSRPCBind
max_tfrag: {5840}
max_rfrag: {5840}
assoc_group: {0}
ctx_num: {2}
Reserved: {0}
Reserved2: {0}
_ctx_items: {88}
ctx_items: {<pykms_RpcBind.MSRPCBind.CtxItemArray object at 0x149c8372a5e0>}

Fri, 17 Dec 2021 08:46:25 DEBUG RPC Bind Response:

MSRPCBindAck
ver_major: {5}
ver_minor: {0}
type: {12}
flags: {19}
representation: {16}
frag_len: {84}
auth_len: {0}
call_id: {1}
max_tfrag: {5840}
max_rfrag: {5840}
assoc_group: {274972479}
SecondaryAddrLen: {5}
SecondaryAddr: {'1688'}
Pad: {b'\x00'}
ctx_num: {2}
ctx_items: {b'\x00\x00\x00\x00\x04]\x88\x8a\xeb\x1c\xc9\x11\x9f\xe8\x08\x00+\x10H`\x02\x00\x00\x00\x
03\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
sec_trailer: {b''}
auth_data: {b''}
pduData: {b''}
pad: {b''}

Fri, 17 Dec 2021 08:46:25 DEBUG RPC Bind Response Bytes:

05000c13100000005400000001000000d016d0163fbf631005003136383800000200000000000000045d888aeb1cc9119fe8
08002b10486002000000030003000000000000000000000000000000000000000000

Fri, 17 Dec 2021 08:46:25 INFO RPC bind acknowledged.
Fri, 17 Dec 2021 08:46:25 INFO RPC bind acknowledged.
Traceback (most recent call last):
File "/home/py-kms/pykms_Client.py", line 364, in <module>
clt_main(with_gui = False)
File "/home/py-kms/pykms_Client.py", line 280, in clt_main
client_create(clt_sock)
File "/home/py-kms/pykms_Client.py", line 221, in client_create
kmsRequest = createKmsRequest()
File "/home/py-kms/pykms_Client.py", line 318, in createKmsRequest
if clt_config['KMSProtocolMajorVersion'] == 4:
KeyError: 'KMSProtocolMajorVersion'
Fri, 17 Dec 2021 08:46:25 WARNING No data received.
Fri, 17 Dec 2021 08:46:25 INFO Connection closed: 127.0.0.1:59122
Fri, 17 Dec 2021 08:46:25 DEBUG sqlite_cmd: /usr/bin/python3 -u /home/sqlite_web/sqlite_web.py -H 0.0.0.0 --read-only -x /home/py-kms/db/pykms_database.db -p 8080
Fri, 17 Dec 2021 08:46:25 INFO Starting a dummy activation to ensure the database file is created
Fri, 17 Dec 2021 08:46:25 DEBUG client_cmd: /usr/bin/python3 -u pykms_Client.py 0.0.0.0 1688 -m Windows10 -n DummyClient -c ae3a27d1-b73a-4734-9878-70c949815218 -V DEBUG -F STDOUT
Fri, 17 Dec 2021 08:46:25 INFO Connecting to 0.0.0.0 on port 1688
Fri, 17 Dec 2021 08:46:25 INFO Connection successful !
Fri, 17 Dec 2021 08:46:25 INFO Connection accepted: 127.0.0.1:59122
Fri, 17 Dec 2021 08:46:25 INFO Sending RPC bind request...
Fri, 17 Dec 2021 08:46:25 INFO RPC bind request received.
Fri, 17 Dec 2021 08:46:25 DEBUG RPC Bind Request Bytes:

05000b13100000007400000001000000d016d0160000000002000000000001007521c8514e845047b0d8ec255555bc060100
0000045d888aeb1cc9119fe808002b10486002000000010001007521c8514e845047b0d8ec255555bc06010000002c1cb76c
12984045030000000000000001000000

Fri, 17 Dec 2021 08:46:25 DEBUG RPC Bind Request:

MSRPCHeader
ver_major: {5}
ver_minor: {0}
type: {11}
flags: {19}
representation: {16}
frag_len: {116}
auth_len: {0}
call_id: {1}
dataLen: {100}
pduData: {b'\xd0\x16\xd0\x16\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x01\x00u!\xc8QN\x84PG\xb0\xd8\x
ec%UU\xbc\x06\x01\x00\x00\x00\x04]\x88\x8a\xeb\x1c\xc9\x11\x9f\xe8\x08\x00+\x10H`\x02\x00\x00\x00\x0
1\x00\x01\x00u!\xc8QN\x84PG\xb0\xd8\xec%UU\xbc\x06\x01\x00\x00\x00,\x1c\xb7l\x12\x98@E\x03\x00\x00\x
00\x00\x00\x00\x00\x01\x00\x00\x00'}
_pad: {0}
pad: {''}
_sec_trailer: {0}
sec_trailer: {''}
auth_dataLen: {0}
auth_data: {''}

MSRPCBind
max_tfrag: {5840}
max_rfrag: {5840}
assoc_group: {0}
ctx_num: {2}
Reserved: {0}
Reserved2: {0}
_ctx_items: {88}
ctx_items: {<pykms_RpcBind.MSRPCBind.CtxItemArray object at 0x149c8372a5e0>}

Fri, 17 Dec 2021 08:46:25 DEBUG RPC Bind Response:

MSRPCBindAck
ver_major: {5}
ver_minor: {0}
type: {12}
flags: {19}
representation: {16}
frag_len: {84}
auth_len: {0}
call_id: {1}
max_tfrag: {5840}
max_rfrag: {5840}
assoc_group: {274972479}
SecondaryAddrLen: {5}
SecondaryAddr: {'1688'}
Pad: {b'\x00'}
ctx_num: {2}
ctx_items: {b'\x00\x00\x00\x00\x04]\x88\x8a\xeb\x1c\xc9\x11\x9f\xe8\x08\x00+\x10H`\x02\x00\x00\x00\x
03\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
sec_trailer: {b''}
auth_data: {b''}
pduData: {b''}
pad: {b''}

Fri, 17 Dec 2021 08:46:25 DEBUG RPC Bind Response Bytes:

05000c13100000005400000001000000d016d0163fbf631005003136383800000200000000000000045d888aeb1cc9119fe8
08002b10486002000000030003000000000000000000000000000000000000000000

Fri, 17 Dec 2021 08:46:25 INFO RPC bind acknowledged.
Fri, 17 Dec 2021 08:46:25 INFO RPC bind acknowledged.
Traceback (most recent call last):
File "/home/py-kms/pykms_Client.py", line 364, in <module>
clt_main(with_gui = False)
File "/home/py-kms/pykms_Client.py", line 280, in clt_main
client_create(clt_sock)
File "/home/py-kms/pykms_Client.py", line 221, in client_create
kmsRequest = createKmsRequest()
File "/home/py-kms/pykms_Client.py", line 318, in createKmsRequest
if clt_config['KMSProtocolMajorVersion'] == 4:
KeyError: 'KMSProtocolMajorVersion'
Fri, 17 Dec 2021 08:46:25 WARNING No data received.
Fri, 17 Dec 2021 08:46:25 INFO Connection closed: 127.0.0.1:59122
Fri, 17 Dec 2021 08:46:25 DEBUG sqlite_cmd: /usr/bin/python3 -u /home/sqlite_web/sqlite_web.py -H 0.0.0.0 --read-only -x /home/py-kms/db/pykms_database.db -p 8080
Unable to open database file in read-only mode. Ensure that the database exists in order to use read-only mode.
```
Now the SQLITE WebUI is not working but the KMS Activation seems to work.

**Comment by simonmicro** [comment]
Hmm, the internal dummy client failed to do his job?! I think the xml is broken... Maybe?

_I have currently no time to look into this... Maybe in the next days? Idk..._

**Comment by lepoarro** [comment]
Got the WebUI working by changing the premissions on pykms_database.db (through docker console):
`chmod 777 /home/py-kms/db/pykms_database.db`
After restarting the docker everything worked. Hope it helps to fix the issue/bug.
