### ISSUE TITLE
Permission error setting up docker-compose via Docs

### ISSUE THREAD

**Issue by pabumake** [Py-KMS-Organization/py-kms#49]
Just tried the current setup related into Docs with following docker-compose:

```yml
version: '3'

services:
  kms:
    image: ghcr.io/py-kms-organization/py-kms:python3
    ports:
      - 1688:1688
      - 8080:8080
    environment:
      - IP=0.0.0.0
      - SQLITE=true
      - HWID=RANDOM
      - LOGLEVEL=INFO
      - LOGFILE=/dev/stdout
    restart: always
    volumes:
      - ./db:/home/py-kms/db
      - /etc/localtime:/etc/localtime:ro
```
Resultet into this Output:
```
`Creating network "py-kms_default" with the default driver
Creating py-kms_kms_1 ... done
Attaching to py-kms_kms_1
kms_1  | Tue, 21 Dec 2021 04:59:32 INFO     Log level: INFO
kms_1  | Tue, 21 Dec 2021 04:59:32 INFO     Setting timzeone to America/Chicago
kms_1  | Tue, 21 Dec 2021 04:59:32 INFO     Setting gid to '1000'.
kms_1  | Tue, 21 Dec 2021 04:59:32 INFO     Setting uid to '100'.
kms_1  | Tue, 21 Dec 2021 04:59:32 INFO     Storing database file to /home/py-kms/db/pykms_database.db
kms_1  | Traceback (most recent call last):
kms_1  |   File "/home/py-kms/pykms_Server.py", line 640, in <module>
kms_1  |     server_main_no_terminal()
kms_1  |   File "/home/py-kms/pykms_Server.py", line 571, in server_main_no_terminal
kms_1  |     server_with_gui()
kms_1  |   File "/home/py-kms/pykms_Server.py", line 564, in server_with_gui
kms_1  |     root = pykms_GuiBase.KmsGui()
kms_1  |   File "/home/py-kms/pykms_GuiBase.py", line 68, in __init__
kms_1  |     tk.Tk.__init__(self, *args, **kwargs)
kms_1  |   File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
kms_1  |     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
kms_1  | _tkinter.TclError: no display name and no $DISPLAY environment variable
kms_1  | 
kms_1  | During handling of the above exception, another exception occurred:
kms_1  | 
kms_1  | Traceback (most recent call last):
kms_1  |   File "/home/py-kms/pykms_Server.py", line 642, in <module>
kms_1  |     server_main_terminal()
kms_1  |   File "/home/py-kms/pykms_Server.py", line 543, in server_main_terminal
kms_1  |     server_check()
kms_1  |   File "/home/py-kms/pykms_Server.py", line 409, in server_check
kms_1  |     check_setup(srv_config, srv_options, loggersrv, where = "srv")
kms_1  |   File "/home/py-kms/pykms_Misc.py", line 549, in check_setup
kms_1  |     logger_create(logger, config, mode = 'a')
kms_1  |   File "/home/py-kms/pykms_Misc.py", line 179, in logger_create
kms_1  |     hand_rotate = RotatingFileHandler(filename = config['logfile'][0], mode = mode, maxBytes = int(config['logsize'] * 1024 * 512),
kms_1  |   File "/usr/lib/python3.9/logging/handlers.py", line 153, in __init__
kms_1  |     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
kms_1  |   File "/usr/lib/python3.9/logging/handlers.py", line 58, in __init__
kms_1  |     logging.FileHandler.__init__(self, filename, mode=mode,
kms_1  |   File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
kms_1  |     StreamHandler.__init__(self, self._open())
kms_1  |   File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
kms_1  |     return open(self.baseFilename, self.mode, encoding=self.encoding,
kms_1  | PermissionError: [Errno 13] Permission denied: '/dev/stdout'
kms_1  | Tue, 21 Dec 2021 04:59:37 INFO     Starting a dummy activation to ensure the database file is created
kms_1  | Traceback (most recent call last):
kms_1  |   File "/home/py-kms/pykms_Client.py", line 364, in <module>
kms_1  |     clt_main(with_gui = False)
kms_1  |   File "/home/py-kms/pykms_Client.py", line 275, in clt_main
kms_1  |     client_check()
kms_1  |   File "/home/py-kms/pykms_Client.py", line 124, in client_check
kms_1  |     check_setup(clt_config, clt_options, loggerclt, where = "clt")
kms_1  |   File "/home/py-kms/pykms_Misc.py", line 549, in check_setup
kms_1  |     logger_create(logger, config, mode = 'a')
kms_1  |   File "/home/py-kms/pykms_Misc.py", line 179, in logger_create
kms_1  |     hand_rotate = RotatingFileHandler(filename = config['logfile'][0], mode = mode, maxBytes = int(config['logsize'] * 1024 * 512),
kms_1  |   File "/usr/lib/python3.9/logging/handlers.py", line 153, in __init__
kms_1  |     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
kms_1  |   File "/usr/lib/python3.9/logging/handlers.py", line 58, in __init__
kms_1  |     logging.FileHandler.__init__(self, filename, mode=mode,
kms_1  |   File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
kms_1  |     StreamHandler.__init__(self, self._open())
kms_1  |   File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
kms_1  |     return open(self.baseFilename, self.mode, encoding=self.encoding,
kms_1  | PermissionError: [Errno 13] Permission denied: '/dev/stdout'`
```

Could "fix" the Permission issue on /dev/stdout temporarly by using a fixed location with .log ending within the docker-compose file to another folder but the DB issue stays.

**Comment by Matthew-Beckett** [comment]
https://github.com/moby/moby/issues/31243#issuecomment-406879017
